[package]
name = "bf-interpreter"
version = "0.1.3"
authors = ["Thomas Lienbacher <lienbacher.tom@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
text_io = "0.1"
failure = "0.1"
ansi_term = "0.11"