[package]
name = "bf-interpreter"
version = "0.3.0"
authors = ["Thomas Lienbacher <lienbacher.tom@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
text_io = "0.1"
ansi_term = "0.12"
num-traits = "0.2"
thiserror = "1.0"
